alias l="exa -1"
alias ll="exa -l"
alias lt="exa -lT"
alias lt1="exa -lTL 1"
alias lt2="exa -lTL 2"
alias ls="ls --color=auto"
alias la="ls -lAh"
alias md="mkdir -p"
alias v="/usr/local/bin/nvim-linux-x86_64/bin/nvim"
alias vi="/usr/local/bin/nvim-linux-x86_64/bin/nvim"
alias vim="/usr/local/bin/nvim-linux-x86_64/bin/nvim"
alias nvim="/usr/local/bin/nvim-linux-x86_64/bin/nvim"
